AWSTemplateFormatVersion: 2010-09-09
Description: sampleLambda
Transform:
- AWS::Serverless-2016-10-31
Resources:
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sampleLambda
      Description: SAM Sample Lambda
      Role: arn:aws:iam::518679741595:role/service-role/Image-conversion-role-h9mzobyt
      Runtime: nodejs10.x
      Handler: src/handlers/scheduled-event-logger.scheduledEventLoggerHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)
      MemorySize: 256
      Timeout: 10
      Tags:
        ASG: GROUP
        COSTCENTER: 1234
      CodeUri: s3://cw-code-upload/19b15514eb608f4a1d8f8026e84f6f1d
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mySampleDynamoDB
      AttributeDefinitions:
      - AttributeName: keyName
        AttributeType: S
      - AttributeName: uploadStatus
        AttributeType: S
      KeySchema:
      - AttributeName: keyName
        KeyType: HASH
      - AttributeName: uploadStatus
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: itemTTL
        Enabled: true
      Tags:
      - Key: ASG
        Value: GROUP
      - Key: COSTCENTER
        Value: 1234
